# Generated by Django 4.2.5 on 2024-02-07 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_models', '0003_cylinder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='product',
            field=models.CharField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cylinder',
            name='tank_name',
            field=models.CharField(),
            preserve_default=False,
        ),
    ]
