# Generated by Django 4.2.5 on 2024-02-08 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_models', '0004_cylinder_product_cylinder_tank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='volume_of_tanks',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='diameter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='height',
            field=models.IntegerField(),
        ),
    ]
