# Generated by Django 4.2.5 on 2024-02-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_models', '0005_cylinder_volume_of_tanks_alter_cylinder_diameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder',
            name='volume_of_tanks',
            field=models.IntegerField(default=0),
        ),
    ]
