# Generated by Django 4.2.5 on 2024-02-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_models', '0007_remove_cylinder_volume_of_tanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='tanks_volume',
            field=models.IntegerField(default=0),
        ),
    ]
