# Generated by Django 4.2.5 on 2024-02-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_models', '0008_cylinder_tanks_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder',
            name='tanks_volume',
            field=models.IntegerField(),
        ),
    ]
