# Generated by Django 4.2.5 on 2024-02-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_models', '0011_alter_cylinder_tank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_name', models.CharField()),
                ('product', models.CharField()),
                ('diameter1', models.IntegerField()),
                ('diameter2', models.IntegerField()),
                ('height1', models.IntegerField()),
                ('height2', models.IntegerField()),
                ('tanks_volume', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='tank_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='tanks_volume',
            field=models.IntegerField(),
        ),
    ]
